modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL="https://github.com/Micaftic/Sparkle-Morpher/issues"
logoFile="sparkle_morpher.png"

[[mixins]]
config = "sparkle_morpher.mixins.json"

[[mixins]]
config = "sparkle_morpher_neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Sparkle's Morpher"
#updateJSONURL=""
displayURL="https://github.com/Micaftic/Sparkle-Morpher"
logoFile="sparkle_morpher.png"
credits=""
authors="Micaftic"
description='''
Sparkle's Morpher (花火火的变身器) - Custom player model system for Minecraft.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${mc_version}"
ordering = "NONE"
side = "BOTH"
