modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
logoFile="sparkle_morpher.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="sparkle_morpher.png"
credits=""
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1,26.2)"
ordering="NONE"
side="BOTH"
