package com.micaftic.morpher.core.gui;

import com.micaftic.morpher.YesSteveModel;
import net.minecraft.resources.Identifier;

/**
 * Texture identifiers for the unified animation roulette. Files are
 * generated by {@code tools/gen_roulette_icons.py} and shipped under
 * {@code assets/sparkle_morpher/texture/roulette/}.
 *
 * <p>All icons are white-on-transparent sprites. The roulette tints
 * them at draw time through the {@link RouletteTheme} palette so a
 * single asset works for every visual state.</p>
 */
public final class RouletteIcons {

    private RouletteIcons() {
    }

    public static final Identifier LOCK = id("texture/roulette/lock.png");
    public static final Identifier UNLOCK = id("texture/roulette/unlock.png");
    public static final Identifier SETTINGS = id("texture/roulette/settings.png");
    public static final Identifier ARROW_LEFT = id("texture/roulette/arrow_left.png");
    public static final Identifier ARROW_RIGHT = id("texture/roulette/arrow_right.png");
    public static final Identifier EDIT = id("texture/roulette/edit.png");

    private static Identifier id(String path) {
        return Identifier.fromNamespaceAndPath(YesSteveModel.MOD_ID, path);
    }
}
